spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///study?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

secure:
  ignored:
    urls: #安全路径白名单
      - /util/**
      - /user/login
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: l0j3Ka38s8CU/hjF85w5T7/EWMruqWIf7jsX55RvAc8= #JWT加解密使用的密钥
  algorithm: HS256 # 使用的算法
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头